<a href="https://colab.research.google.com/github/PabloAndree/Python_PA/blob/main/Pandas-Clase%205ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >


<h1 align=center><font size = 5> VARIABLES Y EXPRESIONES

</font></h1>

---

## Tabla de Contenidos

<div class="alert alert-block alert-info" style="margin-top: 20px">

<font size = 3>
    
1. <a href="#item31">Introducción al entorno Python</a>  
2. <a href="#item31">Sentencias IF</a>  
3. <a href="#item31">Sentencias While</a>  
4. <a href="#item31">Sentencias For</a>  

</font>
</div>

---

#1. Introducción al entorno Python

### Verificando la versión de Python

In [ ]:
!python3

Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
KeyboardInterrupt
>>> 
KeyboardInterrupt
>>> 

### Ejecutando en Python

In [ ]:
print("Hello Python interpreter!")

### Variables en Python

In [ ]:
message = "Hello Python world!"
print(message)

In [ ]:
name = 'jhon'
curse = 'programación'
nota = 20

In [ ]:
print(f"Bienvenido al curso {name}, que te vaya muy bien en el curso de {curse}. La nota mínima para aprobar es: {nota}")

Bienvenido al curso jhon, que te vaya muy bien en el curso de programación. La nota mínima para aprobar es: 20


Escriba un programa que lea el nombre del estudiante y le dé un mensaje de bienvenida al curso.


In [ ]:
name = input('por favor, indique su nombre: ')
print(f"Bienvenido al curso de progración {name}" )

por favor, indique su nombre: pepe
Bienvenido al curso de progración pepe


In [ ]:
print(f"Bienvenido al curso {name}")

Bienvenido al curso jhon


### Usando variables con strings

In [ ]:
first_name = "John"
last_name = "Caballero"

full_name = f"{first_name} {last_name}"
print(full_name)


John Caballero


In [ ]:
first_name = input('Ingrese el primer nombre: ')
last_name = input('Ingrese el apellido: ')

full_name = f"{first_name} {last_name}"
print(f"Bienvenido {full_name}!")


Ingrese el primer nombre: pepe
Ingrese el apellido: perez
Bienvenido pepe perez!


In [ ]:
print(f"Hola, {full_name.title()}!")

In [ ]:
message = f"Hola, {full_name.title()}!"
print(message)

In [ ]:
print("Python")

In [ ]:
print("Python's")

Python's


In [ ]:
print("\tPython")

	Python


In [ ]:
print("\nPython")


Python


In [ ]:
print("Languages:\nPython\nC\nJavaScript")

Languages:
Python
C
JavaScript


In [ ]:
print("Languages:\n\tPython\n\tC\n\tJavaScript")

Languages:
	Python
	C
	JavaScript


### Espacios en python

In [ ]:
favorite_language = 'python '
favorite_language

In [ ]:
favorite_language.rstrip()

In [ ]:
favorite_language

In [ ]:
favorite_language = 'python '
favorite_language = favorite_language.rstrip()
favorite_language

In [ ]:
favorite_language = ' python '
favorite_language

In [ ]:
favorite_language.rstrip()

In [ ]:
favorite_language.lstrip()

In [ ]:
favorite_language.strip()

### Problemas comunes

In [ ]:
message = "El libro 'Harry Potter' fue un best seller"
print(message)

In [ ]:
message = 'One of Python's strengths is its diverse community.'
print(message)

### Números

In [ ]:
2 + 3

In [ ]:
3 ** 2

In [ ]:
(2 + 3) * 4

### Floats

In [ ]:
0.1 + 0.1

In [ ]:
type(10.0)

float

In [ ]:
2 * 0.2

In [ ]:
round(0.25 + 0.12, 1)

0.4

### Enteros y Floats

In [ ]:
type(4/2)


float

In [ ]:
1 + 2.0

In [ ]:
1*3.0

### Guiones bajos en números

In [ ]:
universe_age = 14_000_000_000
print(universe_age)

### Asignación Múltiple

In [ ]:
a, b = 1, 2
b

In [ ]:
x, y, z = 0, 0, 0

In [ ]:
y

### Constantes

In [ ]:
MAX_CONNECTIONS = 5000

<b> Ejercicio </b>

Usa una variable para representar un número. Luego, usando esa variable, cree un mensaje que revele su número. Imprime ese mensaje.

Doble-click __aquí__ para ver la solución.
<!-- La respuesta es:
num = 12
print(f"El número es {num}")
-->



### Comentarios

In [ ]:
# Código para saludar.
print("Hola programadores de Python!")

### El Zen de Python

In [ ]:
import this

### Introducción a listas

In [ ]:
a = ['John', 'Ricardo', 'Marcelo', 'Heidy', 'Nataly']
a

In [ ]:
a = [1, 10, 4, 5, 99.0]
a

In [ ]:
a = [1, 10, 4, 5, 'Nataly']
a

In [ ]:
a = [1, 10, 4, 5, None]
a

In [ ]:
a = [1, 10, 4, 5, [2, 3, 8]]
a

In [ ]:
a[0]

In [ ]:
a[3]

In [ ]:
a[4][1]

# 2. Sentencias IF

In [ ]:
cars = ['audi', 'bmw', 'subaru', 'toyota']

for car in cars:
  if car == 'bmw':
    print(car.upper())
  else:
    print(car.title())

### Igualdades

In [ ]:
1 = 2

In [ ]:
1 == 2

In [ ]:
2 == 2

In [ ]:
2 == 2.0

In [ ]:
car = 'bmw'
car == 'bmw'

In [ ]:
car = 'audi'
car == 'bmw'

Ignorando Mayusculas en igualdades

In [ ]:
car = 'Audi'
car == 'audi'

In [ ]:
car.lower()

In [ ]:
car.upper()

In [ ]:
car = 'Audi'
car.lower() == 'audi'

### Desigualdades

In [ ]:
1 != 2

In [ ]:
'Audi' != 'audi'

In [ ]:
2 != 2.0

In [ ]:
requested_topping = 'champiñones'

if requested_topping != 'Anchoas':
  print("Sostén las Anchoas!")


### Comparar Números

In [ ]:
age = 18
age == 18

In [ ]:
answer = 17

if answer != 42:
  print("Respuesta incorrecta, intenta nuevamente!")

In [ ]:
answer = int(input('Ingrese su respuesta: '))

if answer != 42:
  print("Respuesta incorrecta, intenta nuevamente!")

In [ ]:
age = 19
age < 21

In [ ]:
age <= 21

In [ ]:
age > 21

In [ ]:
age >= 21

### Condicionales múltiples

In [ ]:
age_0 = 22
age_1 = 18
age_0 >= 21 and age_1 >= 21

In [ ]:
age_1 = 22
age_0 >= 21 and age_1 >= 21

In [ ]:
(age_0 >= 21) and (age_1 >= 21)

In [ ]:
age_0 = 22
age_1 = 18
age_0 >= 21 or age_1 >= 21

In [ ]:
age_0 = 18
age_0 >= 21 or age_1 >= 21

### Comprobar si un valor está en una lista

In [ ]:
my_list = ['Aaron', 'Edwin', 'Brandon', 'Carlos']

'John' in my_list



False

In [ ]:
lenguages = ['R', 'Python', 'C']
lenguages

In [ ]:
lenguages = ['R', 'Python', 'C']
'Python' in lenguages

In [ ]:
'Java' in lenguages

### Comprobar si un valor no está en una lista

In [ ]:
banned_users = ['andrew', 'carolina', 'david']
user = 'marie'

if user not in banned_users:
  print(f"{user.title()}, no se encuentra en la lista de no deseados.")

In [ ]:
banned_users = ['andrew', 'carolina', 'david']
user = str(input('Escriba su primer nombre '))

if user not in banned_users:
  print(f"{user.title()}, no se encuentra en la lista de no deseados.")

In [ ]:
a = int(input('escribe un número: '))

In [ ]:
a

### Condicionales

In [ ]:
game_active = True
can_edit = False

In [ ]:
car = 'subaru'
print("Is car == 'subaru'? I predict True.")
print(car == 'subaru')

print("\nIs car == 'audi'? I predict False.")
print(car == 'audi')

### Sentencias simples con IF

In [ ]:
age = 19
if age >= 18:
  print("Ya tienes edad suficiente para votar!")

In [ ]:
age = 19
if age >= 18:
  print("Ya tienes edad suficiente para votar!")
  print("Todavía no te has registrado?")

### Sentencias else-IF

In [ ]:
age = 17
if age >= 18:
  print("Ya tienes edad suficiente para votar!")
  print("Todavía no te has registrado?")
else:
  print("Lo sentimos, eres muy joven para votar!")
  print("Por favor registrate cuando cumplas 18!")

In [ ]:
age = 12

if age < 4:
  print("Your admission cost is $0.")
elif age < 18:
  print("Your admission cost is $25.")
else:
  print("Your admission cost is $40.")

In [ ]:
age = 12

if age < 4:
  price = 0
elif age < 18:
  price = 25
else:
  price = 40

print(f"Your admission cost is ${price}.")


### Múltiples bloques

In [ ]:
age = 12

if age < 4:
  price = 0
elif age < 18:
  price = 25
elif age < 65:
  price = 40
else:
  price = 20

print(f"Your admission cost is ${price}.")

### Ignorando el bloque else

In [ ]:
age = 12

if age < 4:
  price = 0
elif age < 18:
  price = 25
elif age < 65:
  price = 40
elif age >= 65:
  price = 20

print(f"Your admission cost is ${price}.")


### Probando múltiples condiciones

In [ ]:
requested_toppings = ['mushrooms', 'extra cheese']

if 'mushrooms' in requested_toppings:
  print("Adding mushrooms.")
if 'pepperoni' in requested_toppings:
  print("Adding pepperoni.")
if 'extra cheese' in requested_toppings:
  print("Adding extra cheese.")

print("\nFinished making your pizza!")

In [ ]:
num1 = float(input('Ingrese el primer número: '))
num2 = float(input('Ingrese el segundo número: '))

if num1 > num2:
  print('num1 es mayor')
else:
  print('num2 es mayor')

<b> Ejercicio 1</b>

Imagina que un extraterrestre acaba de ser derribado en un juego. Cree una variable llamada alien_color y asígnele un valor de 'verde', 'amarillo' o 'rojo'.

Escribe una declaración if para probar si el color del extraterrestre es verde. Si es así, imprime un mensaje de que el jugador acaba de ganar 5 puntos.

<b> Ejercicio 2</b>

Elija un color para un extraterrestre como lo hizo en el Ejercicio anterior y escriba una cadena if-else.

Si el alienígena es verde, imprime un mensaje de que el jugador obtuvo 5 puntos.
Si el alienígena es amarillo, imprime un mensaje de que el jugador obtuvo 10 puntos.
Si el alienígena es rojo, imprime un mensaje de que el jugador obtuvo 15 puntos.

<b>Ejercicio</b>

Pregunte al usuario su edad, si esta es mayor igual a 18 años, imprima un mensaje que indique que puede votar, si la presona es menor que 18 años ,imprima un mensaje de que aun no cumple mayoría de edad, finalmente si la persona supera los 65 años, imprima un mensaje de que supera el umbral de edad para votar.

Extra: A las personas que sean aptas para votar preguntele su candidato y guadelo en una lista la cual se imprimirá el finalizar el programa.


# Sentencias While

In [ ]:
current_number = 1
while current_number <= 5:
    print(current_number)
    current_number += 1

In [ ]:
prompt = "\nDime algo y lo repetire:"
prompt += "\nEscribe 'quit' para finalizar. "

message = ""
while message != 'salir':
  message = input(prompt)
  print(message)

### Usado una constante

In [ ]:
active = True
while active:
  message = input(prompt)

  if message == 'salir':
    active = False
  else:
    print(message)

### Break

In [ ]:
while True:
       city = input(prompt)

       if city == 'salir':
           break
       else:
           print(f"Me encantaría ir a {city.title()}!")

### Continue

In [ ]:
current_number = 0

while current_number < 10:
  current_number += 1
  if current_number % 2 == 0:
    continue
  print(current_number)

### Evitando Loops infinitos

In [ ]:
x = 1
while x <= 5:
    print(x)
    x += 1

In [ ]:
# This loop runs forever!
x = 1
while x <= 5:
    print(x)

<b> Ejercicio 1</b>

Escriba un ciclo que solicite al usuario que ingrese una serie de ingredientes para la pizza hasta que ingrese un valor de 'salir'. A medida que ingresen cada ingrediente, imprima un mensaje que diga que agregará ese ingrediente a su pizza.

<b> Ejercicio 2</b>

Un cine cobra diferentes precios de boletos dependiendo de la edad de una persona. Si una persona es menor de 3 años, la entrada es gratuita; si son entre 3 y 12, el boleto cuesta s/. 10; y si son mayores de 12 años, el boleto cuesta s/. 15. Escriba un ciclo en el que pregunte a los usuarios su edad y luego dígales el costo de su boleto de cine.

# 3. Sentencia For

In [ ]:
magicians = ['alice', 'david', 'carolina']
for magician in magicians:
  print(f"{magician.title()}, that was a great trick!")

In [ ]:
magicians = ['alice', 'david', 'carolina']
for magician in magicians:
  print(f"{magician.title()}, that was a great trick!")
  print(f"I can't wait to see your next trick, {magician.title()}.\n")

In [ ]:
magicians = ['alice', 'david', 'carolina']

for magician in magicians:
    print(f"{magician.title()}, that was a great trick!")
    print(f"I can't wait to see your next trick, {magician.title()}.\n")

print("Thank you, everyone. That was a great magic show!")

### Olvidando la identación

In [ ]:
magicians = ['alice', 'david', 'carolina']
for magician in magicians:
print(magician)

In [6]:
!pip install numpy

In [7]:
import numpy as np

In [10]:
mat_18= np.array([[1,2],[3,4]])
mat_19= np.array([[5,6],[7,8]])

print(f"La primera matriz es: \n {mat_18} \n")
print(f"La segunda matriz es: \n {mat_19} \n")
print(f"La suma resultante de la matrices es: \n {mat_18 + mat_19} \n")

La primera matriz es: 
 [[1 2]
 [3 4]] 

La segunda matriz es: 
 [[5 6]
 [7 8]] 

La suma resultante de la matrices es: 
 [[ 6  8]
 [10 12]] 



In [14]:
mat_18= np.array([[1,2],[3,4]])
mat_19= np.array([[5,6],[7,8]])

print(f"La primera matriz es: \n {mat_18} \n")
print(f"La segunda matriz es: \n {mat_19} \n")
print(f"La suma resultante de la matrices es: \n {np.add(mat_18,mat_19)} \n")

La primera matriz es: 
 [[1 2]
 [3 4]] 

La segunda matriz es: 
 [[5 6]
 [7 8]] 

La suma resultante de la matrices es: 
 [[ 6  8]
 [10 12]] 



In [13]:
mat_18= np.array([[1,2],[3,4]])
mat_19= np.array([[5,6],[7,8]])

print(f"La primera matriz es: \n {mat_18} \n")
print(f"La segunda matriz es: \n {mat_19} \n")
print(f"La suma resultante de la matrices es: \n {mat_19 - mat_18} \n")

La primera matriz es: 
 [[1 2]
 [3 4]] 

La segunda matriz es: 
 [[5 6]
 [7 8]] 

La suma resultante de la matrices es: 
 [[4 4]
 [4 4]] 



In [ ]:
mat_18= np.array([[1,2],[3,4]])
mat_19= np.array([[5,6],[7,8]])

print(f"La primera matriz es: \n {mat_18} \n")
print(f"La segunda matriz es: \n {mat_19} \n")
print(f"La suma resultante de la matrices es: \n {mat_18 + mat_19} \n")

In [15]:
mat_18= np.array([[1,2],[3,4]])
mat_19= np.array([[5,6],[7,8]])

print(f"La primera matriz es: \n {mat_18} \n")
print(f"La segunda matriz es: \n {mat_19} \n")
print(f"La suma resultante de la matrices es: \n {np.subtract(mat_19,mat_18)} \n")

La primera matriz es: 
 [[1 2]
 [3 4]] 

La segunda matriz es: 
 [[5 6]
 [7 8]] 

La suma resultante de la matrices es: 
 [[4 4]
 [4 4]] 



In [ ]:
mat_18= np.array([[1,2],[3,4]])
mat_19= np.array([[5,6],[7,8]])

print(f"La primera matriz es: \n {mat_18} \n")
print(f"La segunda matriz es: \n {mat_19} \n")
print(f"La suma resultante de la matrices es: \n {np.multiply(mat_18,mat_19)} \n")

In [16]:
mat_18= np.array([[1,2,3],[4,5,6]])
mat_19= np.array([[1,2],[3,4],[5,6]])

print(f"La primera matriz es: \n {mat_18} \n")
print(f"El numero de dimensiones de la matriz es: \n {mat_18.ndim} \n")
print(f"El tamaño de las dimensiones de la matriz es: \n {mat_18.shape} \n")


La primera matriz es: 
 [[1 2 3]
 [4 5 6]] 

El numero de dimensiones de la matriz es: 
 2 



In [18]:
print(f"La segunda matriz es: \n {mat_19} \n")
print(f"El numero de dimensiones de la matriz es: \n {mat_19.ndim} \n")
print(f"El tamaño de las dimensiones de la matriz es: \n {mat_19.shape} \n")

La segunda matriz es: 
 [[1 2]
 [3 4]
 [5 6]] 

El numero de dimensiones de la matriz es: 
 2 

El tamaño de las dimensiones de la matriz es: 
 (3, 2) 



In [19]:
mat_18 + mat_19

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [20]:
mat_18= np.array([[1,2],[3,4]])
mat_19= np.array([[5,6],[7,8]])

print(f"La primera matriz es: \n {mat_18} \n")
print(f"La segunda matriz es: \n {mat_19} \n")
print(f"La suma resultante de la matrices es: \n {np.multiply(mat_18,mat_19)} \n")

La primera matriz es: 
 [[1 2]
 [3 4]] 

La segunda matriz es: 
 [[5 6]
 [7 8]] 

La suma resultante de la matrices es: 
 [[ 5 12]
 [21 32]] 



In [22]:
mat_18.dot(mat_19)

array([[19, 22],
       [43, 50]])

In [23]:
np.dot(mat_18, mat_19)

array([[19, 22],
       [43, 50]])

In [28]:
n1= np.random.randint(5)
n1

4

In [30]:
mat_20 = np.random.randint(10, size=5)
mat_20

array([6, 6, 1, 7, 7])

In [33]:
mat_20 = np.random.randint(100, size=(3,4))
mat_20

array([[95,  0, 86, 87],
       [15, 82, 39, 48],
       [ 7, 71, 93, 79]])

In [35]:
mat_22 = np.random.rand(10)
mat_22

array([0.04965985, 0.61313487, 0.24036398, 0.56233359, 0.31843784,
       0.27709833, 0.33264449, 0.31169127, 0.70730784, 0.51170601])

In [36]:
mat_23 = np.random.rand(3,3)
mat_23

array([[0.02838142, 0.49361439, 0.50941147],
       [0.99222571, 0.9350503 , 0.7306193 ],
       [0.53981267, 0.60183957, 0.00216921]])

In [39]:
mat_24 = np.random.choice([3,5,9,5,11], size=3)
mat_24

array([5, 3, 3])

In [40]:
mat_24.ndim

1

In [41]:
mat_25 = np.random.choice([3,5,9,5,11], size=(2,2))
mat_25

array([[3, 5],
       [5, 5]])

In [42]:
mat_26 = np.random.choice([3,5,9,5,11], size=(2,2,2))
mat_26

array([[[11,  5],
        [ 5, 11]],

       [[ 3,  5],
        [ 3, 11]]])

In [43]:
mat_26.ndim

3

In [45]:
mat_27=np.array([[0,1,2],[4,2,3]])
print(f"La matriz de datos es \n {mat_27} \n")
print(f"La naturaleza de los datos es \n {type(mat_27)} \n")
print(f"El numero de dimensiones del arreglo es \n {mat_27.ndim} \n")
print(f"El tamañ0 de las dimensiones del arreglo es \n {mat_27.shape} \n")
print(f"La suma de todos los elementos de la matriz es \n {np.sum(mat_27)} \n")
print(f"La suma de los valores a nivel de columnas es \n {np.sum(mat_27,axis=0)} \n")
print(f"La suma de los valores a nivel de filas es \n {np.sum(mat_27,axis=1)} \n")

La matriz de datos es 
 [[0 1 2]
 [4 2 3]] 

La naturaleza de los datos es 
 <class 'numpy.ndarray'> 

El numero de dimensiones del arreglo es 
 2 

El tamañ0 de las dimensiones del arreglo es 
 (2, 3) 

La suma de todos los elementos de la matriz es 
 12 

La suma de los valores a nivel de columnas es 
 [4 3 5] 

La suma de los valores a nivel de filas es 
 [3 9] 



In [47]:
mat_28 = np.array([[1,1],[1,1]])
mat_29 = np.array([[8,8],[8,8]])
np.concatenate((mat_28,mat_29))

array([[1, 1],
       [1, 1],
       [8, 8],
       [8, 8]])

In [49]:
np.concatenate([mat_28, mat_29], axis=0)

array([[1, 1],
       [1, 1],
       [8, 8],
       [8, 8]])

In [50]:
np.concatenate([mat_28, mat_29], axis=1)

array([[1, 1, 8, 8],
       [1, 1, 8, 8]])

In [51]:
import numpy as np
import pandas as pd

In [52]:
datos_4 = np.array(10)
datos_4


array(10)

In [53]:
type(datos_4)

numpy.ndarray

In [54]:
datos_4.min()

10

In [57]:
datos_4.mean()


10.0

In [56]:
datos_4.sum()

10

In [59]:
mat_1 = np.random.uniform(5,6,10)
mat_1

array([5.38693024, 5.42140987, 5.10184003, 5.02778866, 5.13111067,
       5.10783733, 5.90944842, 5.17177577, 5.81416799, 5.09326799])

In [60]:
mat_2 = np.random.uniform(1,2,10)
mat_2

array([1.34780153, 1.99093944, 1.12382102, 1.61076364, 1.74350683,
       1.6241272 , 1.47074198, 1.75801602, 1.80996263, 1.20375213])

In [61]:
mat_3 = np.random.uniform(-1,1,10)
mat_3

array([-0.22899795, -0.14155394, -0.9398322 ,  0.02466183, -0.18191886,
        0.78362517,  0.13416441,  0.77233997, -0.59610871,  0.52418939])

In [62]:
mat_1.ndim

1

In [63]:
mat_1 + mat_2 + mat_3

array([6.50573383, 7.27079537, 5.28582885, 6.66321414, 6.69269865,
       7.5155897 , 7.51435481, 7.70213176, 7.02802192, 6.8212095 ])

In [68]:
##Obtener una serie a partir de una matriz (1D)
ser_mat_1=pd.Series(mat_1)
ser_mat_1

0    5.386930
1    5.421410
2    5.101840
3    5.027789
4    5.131111
5    5.107837
6    5.909448
7    5.171776
8    5.814168
9    5.093268
dtype: float64

In [69]:
ser_mat_2=pd.Series(mat_2)
ser_mat_2

0    1.347802
1    1.990939
2    1.123821
3    1.610764
4    1.743507
5    1.624127
6    1.470742
7    1.758016
8    1.809963
9    1.203752
dtype: float64

In [70]:
ser_mat_3=pd.Series(mat_3)
ser_mat_3

0   -0.228998
1   -0.141554
2   -0.939832
3    0.024662
4   -0.181919
5    0.783625
6    0.134164
7    0.772340
8   -0.596109
9    0.524189
dtype: float64

In [71]:
%whos

Variable    Type       Data/Info
--------------------------------
datos_4     ndarray    : 1 elems, type `int64`, 8 bytes
mat_1       ndarray    10: 10 elems, type `float64`, 80 bytes
mat_18      ndarray    2x2: 4 elems, type `int64`, 32 bytes
mat_19      ndarray    2x2: 4 elems, type `int64`, 32 bytes
mat_2       ndarray    10: 10 elems, type `float64`, 80 bytes
mat_20      ndarray    3x4: 12 elems, type `int64`, 96 bytes
mat_22      ndarray    10: 10 elems, type `float64`, 80 bytes
mat_23      ndarray    3x3: 9 elems, type `float64`, 72 bytes
mat_24      ndarray    3: 3 elems, type `int64`, 24 bytes
mat_25      ndarray    2x2: 4 elems, type `int64`, 32 bytes
mat_26      ndarray    2x2x2: 8 elems, type `int64`, 64 bytes
mat_27      ndarray    2x3: 6 elems, type `int64`, 48 bytes
mat_28      ndarray    2x2: 4 elems, type `int64`, 32 bytes
mat_29      ndarray    2x2: 4 elems, type `int64`, 32 bytes
mat_3       ndarray    10: 10 elems, type `float64`, 80 bytes
n1          int        4
np

In [72]:
ser_mat_4 = ser_mat_1 + ser_mat_2 + ser_mat_3
ser_mat_4

0    6.505734
1    7.270795
2    5.285829
3    6.663214
4    6.692699
5    7.515590
6    7.514355
7    7.702132
8    7.028022
9    6.821210
dtype: float64

In [73]:
ser_mat_4.describe()

count    10.000000
mean      6.899958
std       0.700787
min       5.285829
25%       6.670585
50%       6.924616
75%       7.453465
max       7.702132
dtype: float64

In [74]:
np.array(["a", "b", "c"])

array(['a', 'b', 'c'], dtype='<U1')

In [75]:
pd.Series(np.array(["a", "b", "c"]))

0    a
1    b
2    c
dtype: object

In [76]:
pd.Series(np.array(["a", "b", "c"]), index=["x","y","z"])

x    a
y    b
z    c
dtype: object

In [77]:
dict_1 = {"Series_1": ser_mat_1,
          "Series_2": ser_mat_2,
          "Series_3": ser_mat_3,
          "Series_4": ser_mat_4}

In [78]:
type(dict_1)

dict

In [80]:
data =pd.DataFrame(dict_1)
data

Series_1  Series_2  Series_3  Series_4
0  5.386930  1.347802 -0.228998  6.505734
1  5.421410  1.990939 -0.141554  7.270795
2  5.101840  1.123821 -0.939832  5.285829
3  5.027789  1.610764  0.024662  6.663214
4  5.131111  1.743507 -0.181919  6.692699
5  5.107837  1.624127  0.783625  7.515590
6  5.909448  1.470742  0.134164  7.514355
7  5.171776  1.758016  0.772340  7.702132
8  5.814168  1.809963 -0.596109  7.028022
9  5.093268  1.203752  0.524189  6.821210

In [81]:
data.head(5)

Series_1  Series_2  Series_3  Series_4
0  5.386930  1.347802 -0.228998  6.505734
1  5.421410  1.990939 -0.141554  7.270795
2  5.101840  1.123821 -0.939832  5.285829
3  5.027789  1.610764  0.024662  6.663214
4  5.131111  1.743507 -0.181919  6.692699

In [82]:
data.shape

(10, 4)

In [83]:
import sys
sys.path[0]

'/content'

In [86]:
data_census = pd.read_csv("data/census.csv", sep=",")

In [87]:
data_census.head(5)

age          workclass   education  education_num       marital_status  \
0   39          State-gov   Bachelors             13        Never-married   
1   50   Self-emp-not-inc   Bachelors             13   Married-civ-spouse   
2   38            Private     HS-grad              9             Divorced   
3   53            Private        11th              7   Married-civ-spouse   
4   28            Private   Bachelors             13   Married-civ-spouse   

           occupation    relationship    race   gender  hours_per_week  \
0        Adm-clerical   Not-in-family   White     Male              40   
1     Exec-managerial         Husband   White     Male              13   
2   Handlers-cleaners   Not-in-family   White     Male              40   
3   Handlers-cleaners         Husband   Black     Male              40   
4      Prof-specialty            Wife   Black   Female              40   

   native_country  greater_than_50k  
0   United-States                 0  
1   United-States                 0  
2   United-States                 0  
3   United-States                 0  
4            Cuba                 0

<b> Ejercicio 1</b>


Piensa en al menos tres tipos de tu pizza favorita. Almacene estos nombres de pizza en una lista y luego use un ciclo for para imprimir el nombre de cada pizza.

Modifique su ciclo for para imprimir una oración usando el nombre de la pizza en lugar de imprimir solo el nombre de la pizza. Para cada pizza, debe tener una línea de salida que contenga una declaración simple como Me gusta la pizza de pepperoni.
Agregue una línea al final de su programa, fuera del bucle for, que indique cuánto le gusta la pizza. El resultado debe constar de tres o más líneas sobre los tipos de pizza que te gustan y luego una oración adicional, como ¡Me encanta la pizza!


<b> Ejercicio 2</b>

Piensa en al menos tres animales diferentes que tengan una característica común. Guarde los nombres de estos animales en una lista y luego use un ciclo for para imprimir el nombre de cada animal.

Modifique su programa para imprimir una declaración sobre cada animal, como Un perro sería una gran mascota.
Agregue una línea al final de su programa indicando lo que estos animales tienen en común. Podría escribir una oración como ¡Cualquiera de estos animales sería una gran mascota!

---

# Gracias por completar este laboratorio!

---
